#!/bin/bash

bq query \
    --use_legacy_sql=false \
    --append_table=false \
    'select distinct voyage_origin_port, port_at_call
    from 
    # data_science.stg_vessel_info 
    # data_science.stg_vessel_ports
      data_science.stg_vessel_tracked_events
    #  where unique_port is not null and left(unique_port,1) <> "-"
    # group by 1
    # order by 1
    '
